"""
PDAX accepted bank / e-wallet codes (case-sensitive).

`beneficiary_bank_code` on a fiat withdrawal must be one of these codes. The
map is name → code; BANK_CODES is the set of valid codes for validation.
"""
from __future__ import annotations

# Display name → PDAX bank code.
BANK_NAME_TO_CODE: dict[str, str] = {
    # ── Banks ──
    "UnionBank": "BAUBPPH",
    "Al-Amanah Islamic Investment Bank": "BAAIBPH",
    "Alipay": "BAALIPH",
    "All Bank": "BAALLPH",
    "Asia United Bank": "BAAUBPH",
    "Australia and New Zealand Bank": "BAANZPH",
    "BDO Unibank": "BABDOPH",
    "BDO Network Bank": "BABDNPH",
    "BPI": "BABOTPH",
    "BPI Direct Banko": "BABPIPH",
    "Bangko Kabayan": "BABAKPH",
    "Banko Mabuhay": "BABAMPH",
    "Bangko Nuestra Señora Del Pilar": "BABNSPH",
    "Bangkok Bank": "BABKBPH",
    "Bank Of America": "BABOAPH",
    "Bank of China": "BABCHPH",
    "Bank of Commerce": "BABOCPH",
    "Bank of Florida": "BABOFPH",
    "Bank of Makati": "BABOMPH",
    "Camalig Bank": "BACAMPH",
    "Cantilan Bank": "BACANPH",
    "Card Bank": "BACABPH",
    "Card SME": "BACASPH",
    "CIMB Bank": "BACIMPH",
    "CTBC Bank": "BACTBPH",
    "Cebuana Lhuillier": "BACLRPH",
    "China Bank": "BACHBPH",
    "China Bank Savings": "BACBSPH",
    "Citibank": "BACITPH",
    "Community Rural Bank of Romblon": "BACRBPH",
    "Country Builders Bank": "BACBBPH",
    "Development Bank of Philippines": "BADEVPH",
    "Dungganon Bank Inc.": "BADUNPH",
    "Deutsche Bank": "BADEBPH",
    "Dumaguete City Development Bank": "BADCDPH",
    "East West Bank": "BAEWBPH",
    "East West Rural Bank": "BAEWRPH",
    "Equicom": "BAEQSPH",
    "First Consolidated Bank": "BAFCBPH",
    "Guagua Rural Bank": "BAGRBPH",
    "GoTyme": "BAGTBPH",
    "HSBC Savings": "BAHSBPH",
    "Isla Bank": "BAISLPH",
    "Industrial & Commercial Bank of China": "BAICOPH",
    "Industrial Bank of Korea": "BAIBKPH",
    "ING Bank": "BAINGPH",
    "Innovative Bank": "BAIVBPH",
    "JPMorgan Chase Bank": "BAJPMPH",
    "KEB Hana Bank": "BAKEBPH",
    "Landbank": "BALABPH",
    "Legazpi Savings Bank": "BALSBPH",
    "Luzon Development Bank": "BALDBPH",
    "Mega ICBC": "BAICBPH",
    "Malayan Bank": "BAMBSPH",
    "Maybank": "BAMAYPH",
    "MCCB": "BAMCCPH",
    "Metrobank": "BAMBAPH",
    "Mizuho Bank": "BAMIZPH",
    "MUFG Bank": "BAMUFPH",
    "Netbank": "BANETPH",
    "Omnipay": "BAOMNPH",
    "PBCom": "BAPBOPH",
    "Pacific Ace Savings Bank": "BAPASPH",
    "Partner Rural Bank": "BAPRBPH",
    "Philippine Business Bank": "BAPBBPH",
    "PNB": "BAPNBPH",
    "PS Bank": "BAPBAPH",
    "PhilTrust Bank": "BAPTCPH",
    "Philippine Veterans Bank": "BAPVBPH",
    "Producers Bank": "BAPCBPH",
    "Producers Savings Bank": "BAPSBPH",
    "Queen City Development Bank": "BAQBAPH",
    "QCRB": "BAQCRPH",
    "Rang-Ay Bank": "BARANPH",
    "RCBC": "BARCBPH",
    "Robinsons Bank": "BAROBPH",
    "Rural Bank of Guinobatan (Asenso)": "BARBOPH",
    "Rural Bank of Digos": "BARBDPH",
    "Rural Bank of Montalban": "BARBMPH",
    "Security Bank": "BASECPH",
    "Seabank": "BASEAPH",
    "Shinhan Bank": "BASHBPH",
    "Standard Chartered Bank": "BASCBPH",
    "Starpay": "BASTAPH",
    "Sterling Bank of Asia": "BASBOPH",
    "Sumimoto Mitsui Banking": "BASMBPH",
    "Sun Savings Bank": "BASSBPH",
    "Tonik Digital Bank": "BATDBPH",
    "Tong Yang Savings Bank": "BATYBPH",
    "UCPB Savings Bank": "BAUCPPH",
    "United Coconut Planters Bank": "BAUCCPH",
    "UNObank": "BAUNOPH",
    "UnionDigital": "BAUDLPH",
    "United Overseas Bank Phils.": "BAUOVPH",
    "Wealth Bank": "BAWEBPH",
    "Yuanta Savings Bank": "BAYSBPH",
    "Maya Bank": "BAMABPH",
    # ── E-wallets ──
    "GCash": "EWGXCPH",
    "Bayad": "EWCISPH",
    "GrabPay": "EWGRAPH",
    "Lulu Money": "EWLLFPH",
    "PalawanPay": "EWPPPH",
    "ShopeePay": "EWSPPPH",
    "TayoCash": "EWTACPH",
    "USSC": "EWUSCPH",
    "Juan Cash": "EWJUCPH",
    "Philippine Digital Asset Exchange": "EWPDXPH",
    "Maya Wallet": "EWPAYPH",
}

# Valid bank codes for `beneficiary_bank_code` validation.
BANK_CODES: frozenset[str] = frozenset(BANK_NAME_TO_CODE.values())


def is_valid_bank_code(code: str) -> bool:
    return code in BANK_CODES
